name: app_farmacia
description: Sistema de Controle de Estoque para Farmácia

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  
  # Estado e Provider
  provider: ^6.1.1
  
  # Banco de dados
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  
  # UUID
  uuid: ^4.2.1
  
  # Internacionalização
  intl: ^0.19.0
  
  # HTTP para APIs
  http: ^1.1.2
  dio: ^5.4.0
  
  # Notificações
  flutter_local_notifications: ^16.3.2
  
  # Launcher para apps externos
  url_launcher: ^6.2.2
  
  # Gráficos
  fl_chart: ^0.65.0
  
  # Geolocalização
  geolocator: ^10.1.0
  permission_handler: ^11.2.0
  
  # Mapas
  google_maps_flutter: ^2.5.3
  
  # Câmera
  camera: ^0.10.5+9
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  
  # Utilities
  path: ^1.8.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
